name: Linting Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install dependencies
        run: make install

      - name: Run Linters
        run: make lint

      - name: Run Tests
        run: make test